version: "2"
services:
  database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: docker-example

  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      DB_URL: jdbc:postgresql://database/docker-example
      DB_USER: admin
      DB_PASSWORD: admin